name: Continuous Integration

on:
  push:
    branches-ignore:
      - release
  pull_request:
    branches-ignore:
      - release

jobs:
  get_branch:
    name: Get Branch
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branchinfo.outputs.branch }}

    steps:
      - name: Store the branch name
        id: branchinfo
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

  tests:
    needs: get_branch
    uses: ./.github/workflows/reusable_tests.yml
    with:
      from_branch: ${{ needs.get_branch.outputs.branch }}
