name: Publish to Stores

on:
  push:
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+"

jobs:
  snapstore:
    name: Publish to Ubuntu Snap Store
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # 'beta' # 'dev', 'alpha', default to: 'stable'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build snap
        run: |
          flutter pub get
          snapcraft
          snapcraft upload --release=edge ./diligence_*.snap
