name: Release
on:
  push:
    branches:
      - main
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - id: latestRelease
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: asartalo/diligence

      - uses: subosito/flutter-action@v1
        with:
          channel: 'dev'

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Get flutter dependencies.
      - run: flutter pub get

      - run: echo "${{ steps.latestRelease.release }})"

      - name: Check if we should release
        id: checkShouldRelease
        run: echo "::set-output name=should::$(pub run --no-sound-null-safety diligence shouldRelease ${{ steps.latestRelease.release }})"

      - run: echo "${{ steps.checkShouldRelease.should }}"

      - if: ${{ steps.checkShouldRelease.should == "yes" }}
        run: "Will release"

      - if: ${{ steps.checkShouldRelease.should != "yes" }}
        run: "Will not release"

      # - name: Install dependencies
      #   run: npm ci

      # - name: Release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: npx semantic-release
