name: Publish to Stores

on:
  workflow_call:
    inputs:
      tag:
        description: "The version tag for this release"
        type: string
        required: true
      version:
        description: "The version for this release"
        type: string
        required: true
    secrets:
      SNAPCRAFT_STORE_CREDENTIALS:
        required: true
      foo:
        required: true

jobs:
  snapstore:
    name: Ubuntu Snap Store
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
      FOO: ${{ secrets.foo }}

    steps:
      - name: Print FOO
        run: "echo ${FOO: -3}"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable" # 'beta' # 'dev', 'alpha', default to: 'stable'

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v2

      - name: Build snap
        run: |
          flutter pub get
          sg lxd -c 'snapcraft --use-lxd'
          snapcraft upload --release=edge ./diligence_*.snap
